version: '3'
networks:
  default:
    name: simplebackend
    external: true
    
      
services:
  typescript-express-app:
    networks:
      - simplebackend
    build: .
    ports: 
      - 3000:3000
    volumes:
      - ./src:/usr/app/src
commands: ['npm', 'run', 'start:prod']